# Generated by Django 5.2.3 on 2025-06-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='avatar_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
