# Generated by Django 5.2.3 on 2025-06-21 03:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='relationship',
            name='connection_level',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
